import random

fornames_m_ru = [
    "Dmitry",
    "Vladislav",
    "Vladimir",
    "Anatoly",
    "Fyodor",
    "Timofey",
    "Vadim",
    "Gleb",
    "Konstantin",
    "Svyatoslav",
    "Pyotr",
    "Eduard",
    "Ivan",
    "Ilya",
    "Yevgeny",
    "Daniil",
    "Aleksey",
    "Igor",
    "Mikhail",
    "Vyacheslav",
    "Maksim",
    "Roman",
    "Vasily",
    "Pavel",
    "Viktor",
    "Sergey",
    "Boris",
    "Nikolai",
    "Kirill",
]

fornames_f_ru = [
    "Lyudmila",
    "Olga",
    "Darya",
    "Ksenia",
    "Irina",
    "Vladislava",
    "Svetlana",
    "Tatyana",
    "Anastasiya",
    "Yelena",
    "Aleksandra",
    "Valentina",
    "Yuliya",
    "Polina",
    "Larisa",
    "Lada",
    "Margarita",
]
patronymics_m_ru = [
    "Dmitriyevich",
    "Antonovich",
    "Anatolyevich",
    "Konstantinovich",
    "Ilyich",
    "Ivanovich",
    "Vladimirovich",
    "Viktorovich",
    "Nikolayevich",
    "Yaroslav",
    "Vasilyevich",
    "Vladislavovich",
    "Vitalyevich",
    "Valentinovich",
    "Vadimovich",
    "Semyonovich",
    "Sergeyevich",
    "Ruslanovich",
    "Romanovich",
    "Mikhailovich",
    "Maksimovich",
    "Lvovich",
    "Kirillovich",
    "Igorevich",
    "Arkadyevich",
    "Arsenyevich",
    "Andreyevich",
    "Aleksandrovich",
    "Alekseyevich",
    "Leonidovich",
    "Nikitich",
    "Petrovich",
]

surnames_m_ru = [
    "Ivanov",
    "Kuznetsov",
    "Petrov",
    "Smirnov",
    "Popov",
    "Belov",
    "Volkov",
    "Novikov",
    "Morozov",
    "Pavlov",
    "Vasilev",
    "Romanov",
    "Makarov",
    "Stepanov",
    "Zakharov",
    "Orlov",
    "Medvedvev",
    "Borisov",
    "Antonov",
    "Zhukov",
    "Konstantinov",
    "Kirillov",
    "Semyonov",
    "Stepanov",
]


def generate_name_m_ru():
    forname_m_ru = random.choice(fornames_m_ru)
    patronymic_m_ru = random.choice(patronymics_m_ru)
    surname_m_ru = random.choice(surnames_m_ru)
    return forname_m_ru + " " + patronymic_m_ru + " " + surname_m_ru
