import random

forenames_m_pl = [
    "Radosław",
    "Czesław",
    "Grzegorz",
    "Sebastian",
    "Jan",
    "Janusz",
    "Amadeusz",
    "Piotr",
    "Paweł",
    "Arkadiusz",
    "Bogdan",
    "Szczepan",
    "Tomasz",
    "Maciej",
    "Jarosław",
    "Jerzy",
    "Konstanty",
    "Krzysztof",
    "Ksawery",
    "Leszek",
    "Łukasz",
    "Maksymilian",
    "Marcin",
    "Marek",
    "Mariusz",
    "Mateusz",
    "Michał",
    "Mieczysław",
    "Patryk",
    "Henryk",
    "Eryk",
    "Rafał",
    "Sławomir",
    "Mirosław",
    "Tadeusz",
    "Wiktor",
    "Władysław",
    "Włodzimierz",
    "Wojciech",
    "Zbigniew",
    "Karol",
    "Ignacy",
    "Andrzej",
    "Zygmunt",
    "Stanisław",
    "Jakub",
    "Artur",
    "Jacek",
    "Przemysław",
    "Bartosz",
    "Kazimierz",
    "Adam",
    "Robert",
    "Kamil",
    "Konrad",
    "Damian",
    "Ryszard",
    "Dawid",
    "Krystian",
    "Ireneusz",
    "Michael",
    "Kacper",
    "Remigiusz",
    "Eugeniusz",
    "Zdzisław",
]

forenames_f_pl = [
    "Czesława",
    "Bronisława",
    "Jarosława",
    "Janina",
    "Izabela",
    "Jadwiga",
    "Barbara",
    "Bożena",
    "Renata",
    "Dagmara",
    "Danuta",
    "Dominika",
    "Elżbieta",
    "Krystyna",
    "Małgorzata",
    "Urszula",
    "Teresa",
    "Magdalena",
    "Katarzyna",
    "Agnieszka",
    "Mirosława",
    "Monika",
    "Edyta",
    "Marzena",
    "Zofia",
    "Iwona",
    "Karolina",
    "Kazimiera",
    "Anna",
    "Joanna",
    "Ewa",
    "Marta",
    "Dorota",
    "Beata",
    "Justyna",
    "Agata",
    "Paulina",
    "Maria",
    "Jolanta",
    "Ewalina",
    "Dominika",
    "Kinga",
    "Weronika",
    "Olga",
    "Jagoda",
    "Zuzanna",
]

surnames_m_pl = [
    "Bratkowski",
    "Kowalski",
    "Baliński",
    "Buczkowski",
    "Burzyński",
    "Drągowski",
    "Lewandowski",
    "Kamiński",
    "Zieliński",
    "Szymański",
    "Kozłowski",
    "Jankowski",
    "Wojciechowski",
    "Kwiatkowski",
    "Piotrowski",
    "Grabowski",
    "Majewski",
    "Jabłoński",
    "Olszewski",
    "Lipiński",
]

surnames_f_pl = [
    "Bratkowska",
    "Kowalska",
    "Balińska",
    "Buczkowska",
    "Burzyńska",
    "Drągowska",
    "Lewandowska",
    "Kamińska",
    "Zieliński",
    "Szymańska",
    "Kozłowska",
    "Jankowska",
    "Wojciechowska",
    "Kwiatkowska",
    "Piotrowska",
    "Grabowska",
    "Majewska",
    "Jabłońska",
    "Olszewska",
    "Lipińska",
]

surnames_n_pl = [
    "Dziura",
    "Dutkiewicz",
    "Adamiak",
    "Pietras",
    "Buczek",
    "Grzegorczyk",
    "Szczygieł",
    "Pietrzyk",
    "Cichoń",
    "Rybak",
    "Szczepaniak",
    "Kaczmarczyk",
]

surnames_mn_pl = surnames_m_pl + surnames_n_pl
surnames_fn_pl = surnames_f_pl + surnames_n_pl


def generate_name_m_pl():
    forename_m_pl = random.choice(forenames_m_pl)
    middlename_m_pl = random.choice(forenames_m_pl)
    surname_m_pl = random.choice(surnames_mn_pl)
    return forename_m_pl + " " + middlename_m_pl + " " + surname_m_pl


def generate_name_f_pl():
    forename_f_pl = random.choice(forenames_f_pl)
    middlename_f_pl = random.choice(forenames_f_pl)
    surname_f_pl = random.choice(surnames_f_pl)
    return forename_f_pl + " " + middlename_f_pl + " " + surname_f_pl
