import random

forenames_m_ru = [
    "Dmitry",
    "Vladislav",
    "Vladimir",
    "Anatoly",
    "Fyodor",
    "Timofey",
    "Vadim",
    "Gleb",
    "Konstantin",
    "Svyatoslav",
    "Pyotr",
    "Eduard",
    "Ivan",
    "Ilya",
    "Yevgeny",
    "Daniil",
    "Aleksey",
    "Igor",
    "Mikhail",
    "Vyacheslav",
    "Maksim",
    "Roman",
    "Vasily",
    "Pavel",
    "Viktor",
    "Sergey",
    "Boris",
    "Nikolai",
    "Kirill",
]

forenames_f_ru = [
    "Lyudmila",
    "Olga",
    "Darya",
    "Ksenia",
    "Irina",
    "Vladislava",
    "Svetlana",
    "Tatyana",
    "Anastasiya",
    "Yelena",
    "Aleksandra",
    "Valentina",
    "Yuliya",
    "Polina",
    "Larisa",
    "Lada",
    "Margarita",
]
patronymics_m_ru = [
    "Dmitriyevich",
    "Antonovich",
    "Anatolyevich",
    "Konstantinovich",
    "Ilyich",
    "Ivanovich",
    "Vladimirovich",
    "Viktorovich",
    "Nikolayevich",
    "Yaroslavovich",
    "Vasilyevich",
    "Vladislavovich",
    "Vitalyevich",
    "Valentinovich",
    "Vadimovich",
    "Semyonovich",
    "Sergeyevich",
    "Ruslanovich",
    "Romanovich",
    "Mikhailovich",
    "Maksimovich",
    "Lvovich",
    "Kirillovich",
    "Igorevich",
    "Arkadyevich",
    "Arsenyevich",
    "Andreyevich",
    "Aleksandrovich",
    "Alekseyevich",
    "Leonidovich",
    "Nikitich",
    "Petrovich",
]

patronymics_f_ru = [
    "Dmitriyevna",
    "Antonevna",
    "Anatolyevna",
    "Konstantinovna",
    "Ilyinichna",
    "Ivanovna",
    "Vladimirovna",
    "Viktorovna",
    "Nikolayevna",
    "Yaroslavovna",
    "Vasilyevna",
    "Vladislavovna",
    "Vitalyevna",
    "Valentinovna",
    "Vadimovna",
    "Semyonovna",
    "Sergeyevna",
    "Ruslanovna",
    "Romanovna",
    "Mikhailovna",
    "Maksimovna",
    "Lvovna",
    "Kirillovna",
    "Igorevna",
    "Arkadyevna",
    "Arsenyevna",
    "Andreyevna",
    "Aleksandrovna",
    "Alekseyevna",
    "Leonidovna",
    "Nikitichna",
    "Petrovna",
]

surnames_m_ru = [
    "Ivanov",
    "Kuznetsov",
    "Petrov",
    "Smirnov",
    "Popov",
    "Belov",
    "Volkov",
    "Novikov",
    "Morozov",
    "Pavlov",
    "Vasilev",
    "Romanov",
    "Makarov",
    "Stepanov",
    "Zakharov",
    "Orlov",
    "Medvedvev",
    "Borisov",
    "Antonov",
    "Zhukov",
    "Konstantinov",
    "Kirillov",
    "Semyonov",
    "Stepanov",
    "Pavlov",
    "Vlasov",
]

surnames_f_ru = [
    "Ivanova",
    "Kuznetsova",
    "Petrova",
    "Smirnova",
    "Popova",
    "Belova",
    "Volkova",
    "Novikova",
    "Morozova",
    "Pavlova",
    "Vasileva",
    "Romanova",
    "Makarova",
    "Stepanova",
    "Zakharova",
    "Orlova",
    "Medvedveva",
    "Borisova",
    "Antonova",
    "Zhukova",
    "Konstantinova",
    "Kirillova",
    "Semyonova",
    "Stepanova",
    "Pavlova",
    "Vlasova",
]


def generate_name_m_ru():
    forename_m_ru = random.choice(forenames_m_ru)
    patronymic_m_ru = random.choice(patronymics_m_ru)
    surname_m_ru = random.choice(surnames_m_ru)
    return forename_m_ru + " " + patronymic_m_ru + " " + surname_m_ru


def generate_name_f_ru():
    forename_f_ru = random.choice(forenames_f_ru)
    patronymic_f_ru = random.choice(patronymics_f_ru)
    surname_f_ru = random.choice(surnames_f_ru)
    return forename_f_ru + " " + patronymic_f_ru + " " + surname_f_ru
